# Generated by Django 5.2.7 on 2025-12-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='source_label',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='song',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_uri',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
