# Generated by Django 5.2.7 on 2025-12-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_song_source_label_song_source_type_song_spotify_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='source_label',
        ),
        migrations.RemoveField(
            model_name='song',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotify_uri',
        ),
        migrations.AddField(
            model_name='song',
            name='prompt',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='song',
            name='source',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
